/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hackinggame;

/**
 *
 * @author SCHOLES
 */

public class Menu extends javax.swing.JFrame {
    
    public String choice;
    public int difficulty;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choiceGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        veasyRB = new javax.swing.JRadioButton();
        EasyRB = new javax.swing.JRadioButton();
        AveRB = new javax.swing.JRadioButton();
        HardRB = new javax.swing.JRadioButton();
        vhardRB = new javax.swing.JRadioButton();
        PlayBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 124, 72));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("Hacking Game");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel2.setText("Choose difficulty level:");

        veasyRB.setBackground(new java.awt.Color(20, 124, 72));
        choiceGroup.add(veasyRB);
        veasyRB.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        veasyRB.setText("v.Easy");
        veasyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veasyRBActionPerformed(evt);
            }
        });

        EasyRB.setBackground(new java.awt.Color(20, 124, 72));
        choiceGroup.add(EasyRB);
        EasyRB.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        EasyRB.setText("Easy");
        EasyRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasyRBActionPerformed(evt);
            }
        });

        AveRB.setBackground(new java.awt.Color(20, 124, 72));
        choiceGroup.add(AveRB);
        AveRB.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        AveRB.setText("Average");
        AveRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AveRBActionPerformed(evt);
            }
        });

        HardRB.setBackground(new java.awt.Color(20, 124, 72));
        choiceGroup.add(HardRB);
        HardRB.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        HardRB.setText("Hard");
        HardRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardRBActionPerformed(evt);
            }
        });

        vhardRB.setBackground(new java.awt.Color(20, 124, 72));
        choiceGroup.add(vhardRB);
        vhardRB.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        vhardRB.setText("v.Hard");
        vhardRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vhardRBActionPerformed(evt);
            }
        });

        PlayBtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        PlayBtn.setText("Play");
        PlayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EasyRB)
                            .addComponent(veasyRB)
                            .addComponent(AveRB)
                            .addComponent(HardRB)
                            .addComponent(vhardRB)
                            .addComponent(PlayBtn))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(veasyRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EasyRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AveRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HardRB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vhardRB)
                .addGap(18, 18, 18)
                .addComponent(PlayBtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayBtnActionPerformed
        // TODO add your handling code here:
        Game game = new Game();
        game.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_PlayBtnActionPerformed

    private void veasyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veasyRBActionPerformed
        // TODO add your handling code here:
        difficulty = 1;
    }//GEN-LAST:event_veasyRBActionPerformed

    private void EasyRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasyRBActionPerformed
        // TODO add your handling code here:
        difficulty = 2;
    }//GEN-LAST:event_EasyRBActionPerformed

    private void AveRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AveRBActionPerformed
        // TODO add your handling code here:
        difficulty = 3;
    }//GEN-LAST:event_AveRBActionPerformed

    private void HardRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardRBActionPerformed
        // TODO add your handling code here:
        difficulty = 4;
    }//GEN-LAST:event_HardRBActionPerformed

    private void vhardRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vhardRBActionPerformed
        // TODO add your handling code here:
        difficulty = 5;
    }//GEN-LAST:event_vhardRBActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public int getDifficulty(){return difficulty;}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AveRB;
    private javax.swing.JRadioButton EasyRB;
    private javax.swing.JRadioButton HardRB;
    private javax.swing.JButton PlayBtn;
    private javax.swing.ButtonGroup choiceGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton veasyRB;
    private javax.swing.JRadioButton vhardRB;
    // End of variables declaration//GEN-END:variables
}
